/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-03-18 08:12:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>ACE WORKS 회원가입</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/memberLayout.css\">\r\n");
      out.write("<script src=\"js/httpRequest.js\"></script>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function combine(event){\r\n");
      out.write("	var front = document.getElementById('hum_num1').value;\r\n");
      out.write("	var back = document.getElementById('hum_num2').value;\r\n");
      out.write("	\r\n");
      out.write("	var addr1 = document.getElementById('sample4_postcode').value;\r\n");
      out.write("	var addr2 = document.getElementById('sample4_roadAddress').value;\r\n");
      out.write("	var addr3 = document.getElementById('sample4_jibunAddress').value;\r\n");
      out.write("	var addr4 = document.getElementById('sample4_detailAddress').value;\r\n");
      out.write("	var addr5 = document.getElementById('sample4_extraAddress').value;\r\n");
      out.write("	\r\n");
      out.write("	var email1 = document.getElementById('email1').value;\r\n");
      out.write("	var email2 = document.getElementById('email2').value;\r\n");
      out.write("	\r\n");
      out.write("	var fullNumber = front + '-' + back;\r\n");
      out.write("	var fullAddr = addr1 + '/' + addr2 + '/' + addr3 + '/' + addr4 + '/' + addr5;\r\n");
      out.write("	var fullEmail = email1 + '@' + email2;\r\n");
      out.write("	\r\n");
      out.write("	document.getElementById('hum_num').value = fullNumber;\r\n");
      out.write("	document.getElementById('addr').value = fullAddr;\r\n");
      out.write("	document.getElementById('email').value = fullEmail;\r\n");
      out.write("	document.getElementById('hum_num').submit();\r\n");
      out.write("	document.getElementById('addr').submit();	\r\n");
      out.write("	document.getElementById('email').submit();	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function email_change(){\r\n");
      out.write("	if(document.join.emails.value == '1'){\r\n");
      out.write("		document.join.email2.disabled = false;\r\n");
      out.write("		document.join.email2.value = \"\";\r\n");
      out.write("		document.join.email2.focus();\r\n");
      out.write("	} else{\r\n");
      out.write("		document.join.email2.disabled = true;\r\n");
      out.write("		document.join.email2.value = document.join.emails.value;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sample4_execDaumPostcode() {\r\n");
      out.write("    new daum.Postcode({\r\n");
      out.write("        oncomplete: function(data) {\r\n");
      out.write("            var roadAddr = data.roadAddress;\r\n");
      out.write("            var extraRoadAddr = '';\r\n");
      out.write("            if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                extraRoadAddr += data.bname;\r\n");
      out.write("            }\r\n");
      out.write("            if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("               extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("            }\r\n");
      out.write("            if(extraRoadAddr !== ''){\r\n");
      out.write("                extraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("            }\r\n");
      out.write("            document.getElementById('sample4_postcode').value = data.zonecode;\r\n");
      out.write("            document.getElementById(\"sample4_roadAddress\").value = roadAddr;\r\n");
      out.write("            document.getElementById(\"sample4_jibunAddress\").value = data.jibunAddress;\r\n");
      out.write("            \r\n");
      out.write("            if(roadAddr !== ''){\r\n");
      out.write("                document.getElementById(\"sample4_extraAddress\").value = extraRoadAddr;\r\n");
      out.write("            } else {\r\n");
      out.write("                document.getElementById(\"sample4_extraAddress\").value = '';\r\n");
      out.write("            }\r\n");
      out.write("            var guideTextBox = document.getElementById(\"guide\");\r\n");
      out.write("            if(data.autoRoadAddress) {\r\n");
      out.write("                var expRoadAddr = data.autoRoadAddress + extraRoadAddr;\r\n");
      out.write("                guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';\r\n");
      out.write("                guideTextBox.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("            } else if(data.autoJibunAddress) {\r\n");
      out.write("                var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("                guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';\r\n");
      out.write("                guideTextBox.style.display = 'block';\r\n");
      out.write("            } else {\r\n");
      out.write("                guideTextBox.innerHTML = '';\r\n");
      out.write("                guideTextBox.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }).open();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("function show(){\r\n");
      out.write("	sendRequest('memberJoin.do',null,showResult,'GET');		\r\n");
      out.write("}\r\n");
      out.write("function showResult(){\r\n");
      out.write("	if(XHR.readyState==4){\r\n");
      out.write("		if(XHR.status==200){\r\n");
      out.write("			var data = XHR.responseText;\r\n");
      out.write("			var divNode = document.all.memberJoin;\r\n");
      out.write("			if(divNode.innerHTML==''){\r\n");
      out.write("				divNode.innerHTML = data;\r\n");
      out.write("			}else{\r\n");
      out.write("				divNode.innerHTML = '';\r\n");
      out.write("			}\r\n");
      out.write("		}		\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("function show2(){\r\n");
      out.write("	sendRequest('companyJoin.do',null,showResult,'GET');		\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function idCheckMsg(){\r\n");
      out.write("	var id = document.join.id.value;\r\n");
      out.write("	var param = 'id='+id;\r\n");
      out.write("	sendRequest('idCheck.do',param,idCheckShow,'GET');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function idCheckShow(){\r\n");
      out.write("	if(XHR.readyState==4){\r\n");
      out.write("		if(XHR.status==200){\r\n");
      out.write("			var data = XHR.responseText;\r\n");
      out.write("			var msgspan = document.getElementById('idCheckMsg');\r\n");
      out.write("			msgspan.innerHTML=data;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<a href=\"login.do\">\r\n");
      out.write("<h2>ACE WORKS</h2>\r\n");
      out.write("</a>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("		<input class=\"push1\" type=\"button\" value=\"회원등록\" onclick=\"show()\">\r\n");
      out.write("		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("		<input class=\"push1\" type=\"button\" value=\"기업등록\" onclick=\"show2()\">\r\n");
      out.write("		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("		<input class=\"push1\" type=\"button\" value=\"돌아가기\" onclick=\"location.href='login.do'\">\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"memberJoin\"></div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
