/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-03-21 17:02:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.schedule;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ace.member.model.MemberDTO;

public final class schedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ace.member.model.MemberDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>schedule</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("#calendar {\r\n");
      out.write("	margin: 10px auto;\r\n");
      out.write("	clear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#month {\r\n");
      out.write("	margin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#calendar td {\r\n");
      out.write("	border-top: 1px solid gray;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sunday {\r\n");
      out.write("	color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".monthday {\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tuesday {\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wednesday {\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thursday {\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".friday {\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".saturday {\r\n");
      out.write("	color: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tdver {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: -42px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".weekName-div {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	display: inline;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("	border: none;\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".year-select {\r\n");
      out.write("	-webkit-appearance: none;\r\n");
      out.write("	-moz-appearance: none;\r\n");
      out.write("	appearance: none;\r\n");
      out.write("	background-color: transparent;\r\n");
      out.write("	border: none;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 5px 10px;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".month-select {\r\n");
      out.write("	-webkit-appearance: none;\r\n");
      out.write("	-moz-appearance: none;\r\n");
      out.write("	appearance: none;\r\n");
      out.write("	background-color: transparent;\r\n");
      out.write("	border: none;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	font-size: 35px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 10px 10px;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	margin-left: 30px;\r\n");
      out.write("	margin-right: 30px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"button\"] {\r\n");
      out.write("	width: 35px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	font-size: 35px;\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#on_art {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	height: 140vh;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("	display: none;\r\n");
      out.write("	z-index: 900;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#on_input {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	height: 140vh;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("	display: none;\r\n");
      out.write("	z-index: 999;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#schedule_form {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	background-color: skyblue;\r\n");
      out.write("	width: 350px;\r\n");
      out.write("	height: 500px;\r\n");
      out.write("}\r\n");
      out.write("#input_form {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	background-color: skyblue;\r\n");
      out.write("	width: 350px;\r\n");
      out.write("	height: 500px;\r\n");
      out.write("}\r\n");
      out.write("#sdiv{\r\n");
      out.write("	clear:both;\r\n");
      out.write("	width:300px;\r\n");
      out.write("	height:425px;\r\n");
      out.write("	background: white;\r\n");
      out.write("	margin: 10px auto;\r\n");
      out.write("}\r\n");
      out.write("#goButton{\r\n");
      out.write("	margin-left:30px;\r\n");
      out.write("	padding-top: 1px;\r\n");
      out.write("	padding-left: 1px;\r\n");
      out.write("	width:20px;\r\n");
      out.write("	height:20px;\r\n");
      out.write("	background-color: silver;\r\n");
      out.write("}\r\n");
      out.write("#ico{\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("#closeButton{\r\n");
      out.write("	float: right;\r\n");
      out.write("	border:none;\r\n");
      out.write("	background: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"js/httpRequest.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	var now = new Date();\r\n");
      out.write("	var year = 0;\r\n");
      out.write("	var criyear = now.getFullYear();\r\n");
      out.write("	var month = 0;\r\n");
      out.write("	var days = ['sunday','monthday','tuesday','wednesday','thursday','friday','saturday'];\r\n");
      out.write("	var firstDay = 0;\r\n");
      out.write("	var count = 0;\r\n");
      out.write("	var lastDate = 0;\r\n");
      out.write("	var row = 0;\r\n");
      out.write("	var idx=0;\r\n");
      out.write("	var com_idx=0;\r\n");
      out.write("	var sort=0;\r\n");
      out.write("	//페이지 실행될때\r\n");
      out.write("	function startPage(pidx,pcom_idx,psort){\r\n");
      out.write("		userInfo(pidx,pcom_idx,psort)\r\n");
      out.write("		callCal(0,0,1);\r\n");
      out.write("	}\r\n");
      out.write("	//유저 정보 기본세팅\r\n");
      out.write("	function userInfo(pidx,pcom_idx,psort){\r\n");
      out.write("		idx=pidx;\r\n");
      out.write("		com_idx=pcom_idx;\r\n");
      out.write("		sort=psort;\r\n");
      out.write("	}\r\n");
      out.write("	//달력 호출\r\n");
      out.write("	function callCal(pyear, pmonth, psort) {\r\n");
      out.write("		row = 0;\r\n");
      out.write("		if (pyear != 0 || pmonth != 0) {\r\n");
      out.write("			now = new Date(pyear, pmonth, 1);\r\n");
      out.write("		}\r\n");
      out.write("		getRow();\r\n");
      out.write("		getTop();\r\n");
      out.write("		\r\n");
      out.write("		createCal(psort);\r\n");
      out.write("	}\r\n");
      out.write("	//유동적으로 변하는 달의 행을 구하는 거시기\r\n");
      out.write("	function getRow() {\r\n");
      out.write("		year = now.getFullYear();\r\n");
      out.write("		month = now.getMonth();\r\n");
      out.write("		lastDate = new Date(year, (month + 1), 0).getDate();\r\n");
      out.write("		firstDay = new Date(year, month, 1).getDay();\r\n");
      out.write("\r\n");
      out.write("		count = firstDay;\r\n");
      out.write("		for (var i = 1; i <= lastDate; i++) {\r\n");
      out.write("			if (count == 6) {\r\n");
      out.write("				count = -1;\r\n");
      out.write("				row += 1;\r\n");
      out.write("			} else if (i == lastDate) {\r\n");
      out.write("				row += 1;\r\n");
      out.write("			}\r\n");
      out.write("			count += 1;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	//달력 만들어주는 함수\r\n");
      out.write("	function createCal() {\r\n");
      out.write("		count = 1;\r\n");
      out.write("		var tableNode = document.getElementById('calendar');\r\n");
      out.write("		tableNode.innerHTML = \"\";\r\n");
      out.write("		for (var j = 1; j <= row; j++) {\r\n");
      out.write("			var trNode = document.createElement('tr');\r\n");
      out.write("			for (var i = 0; i <= 6; i++) {\r\n");
      out.write("				if (count == 1 && firstDay != 0) {\r\n");
      out.write("					var voidTdNode = document.createElement('td');\r\n");
      out.write("					voidTdNode.setAttribute('colspan', firstDay);\r\n");
      out.write("					voidTdNode.setAttribute('class', 'voidTdNode');\r\n");
      out.write("					trNode.appendChild(voidTdNode);\r\n");
      out.write("					i = firstDay;\r\n");
      out.write("				}\r\n");
      out.write("				var tdNode = document.createElement('td');\r\n");
      out.write("				tdNode.setAttribute('onclick', 'showOnArt('+year+','+month +','+ count+','+i+')');\r\n");
      out.write("				var tdDivNode = document.createElement('div');\r\n");
      out.write("				tdDivNode.setAttribute('class', days[i]);\r\n");
      out.write("				tdDivNode.setAttribute('id', 'tdver');\r\n");
      out.write("				var tdDateText = document.createTextNode(count);\r\n");
      out.write("				tdDivNode.appendChild(tdDateText);\r\n");
      out.write("				tdNode.appendChild(tdDivNode);\r\n");
      out.write("				var tdListNode = document.createElement('div');\r\n");
      out.write("				tdNode.appendChild(tdListNode);\r\n");
      out.write("				trNode.appendChild(tdNode);\r\n");
      out.write("				if (count == lastDate && i != 6) {\r\n");
      out.write("					var voidTdNode = document.createElement('td');\r\n");
      out.write("					voidTdNode.setAttribute('colspan', 6 - i);\r\n");
      out.write("					voidTdNode.setAttribute('class', 'voidTdNode');\r\n");
      out.write("					trNode.appendChild(voidTdNode);\r\n");
      out.write("					i = 7;\r\n");
      out.write("				}\r\n");
      out.write("				count += 1;\r\n");
      out.write("			}\r\n");
      out.write("			tableNode.appendChild(trNode);\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	//고정되는 달력의 상단부분\r\n");
      out.write("	function getTop() {\r\n");
      out.write("		var hDiv = document.getElementById('month');\r\n");
      out.write("		hDiv.setAttribute('style', 'text-align:center;')\r\n");
      out.write("		getYear(hDiv);\r\n");
      out.write("		getMonth(hDiv);\r\n");
      out.write("	}\r\n");
      out.write("	//연도 동적으로 바꿀수 있게 하는 함수\r\n");
      out.write("	function getYear(hDiv) {\r\n");
      out.write("		var hyear = hDiv.firstChild;\r\n");
      out.write("		hyear.innerHTML = \"\";\r\n");
      out.write("		var hySelect = document.createElement('select');\r\n");
      out.write("		hySelect.setAttribute('class', 'year-select');\r\n");
      out.write("\r\n");
      out.write("		for (var i = criyear - 20; i <= criyear + 20; i++) {\r\n");
      out.write("			var opNode = document.createElement('option');\r\n");
      out.write("			opNode.setAttribute('value', i);\r\n");
      out.write("			if (i == year) {\r\n");
      out.write("				opNode.setAttribute('selected', 'selected');\r\n");
      out.write("			}\r\n");
      out.write("			opNode.innerHTML = i;\r\n");
      out.write("			hySelect.appendChild(opNode);\r\n");
      out.write("		}\r\n");
      out.write("		hySelect.setAttribute('onchange', 'callCal(this.value,'+month+')');\r\n");
      out.write("		hyear.appendChild(hySelect);\r\n");
      out.write("	}\r\n");
      out.write("	//월 동적으로 바꿀수 있게하는 함수\r\n");
      out.write("	function getMonth(hDiv) {\r\n");
      out.write("		var hmonth = hDiv.lastChild;\r\n");
      out.write("		hmonth.innerHTML = \"\";\r\n");
      out.write("		var hText = document.createElement('select');\r\n");
      out.write("		hText.setAttribute('class', 'month-select');\r\n");
      out.write("		for (var i = 0; i <= 11; i++) {\r\n");
      out.write("			var opNode = document.createElement('option');\r\n");
      out.write("			opNode.setAttribute('value', i);\r\n");
      out.write("			if (i == month) {\r\n");
      out.write("				opNode.setAttribute('selected', 'selected');\r\n");
      out.write("			}\r\n");
      out.write("			opNode.innerHTML = i + 1;\r\n");
      out.write("			hText.appendChild(opNode);\r\n");
      out.write("		}\r\n");
      out.write("		hText.setAttribute('onchange', 'callCal(' + year + ',this.value)');\r\n");
      out.write("\r\n");
      out.write("		var hlp = document.createElement('input');\r\n");
      out.write("		hlp.setAttribute('type', 'button');\r\n");
      out.write("		hlp.setAttribute('value', '<');\r\n");
      out.write("		hlp.setAttribute('onclick', 'callCal('+year+','+(month-1)+')');\r\n");
      out.write("		var hrp = document.createElement('input');\r\n");
      out.write("		hrp.setAttribute('type', 'button');\r\n");
      out.write("		hrp.setAttribute('value', '>');\r\n");
      out.write("		hrp.setAttribute('onclick','callCal('+year+','+(month+1)+')');\r\n");
      out.write("		hmonth.appendChild(hlp);\r\n");
      out.write("		hmonth.appendChild(hText);\r\n");
      out.write("		hmonth.appendChild(hrp);\r\n");
      out.write("		hDiv.appendChild(hmonth);\r\n");
      out.write("	}\r\n");
      out.write("	// 달력의 분류 바꿔주는 함수\r\n");
      out.write("	function changeSort(psort){\r\n");
      out.write("		alert(psort);\r\n");
      out.write("		sort=psort;\r\n");
      out.write("	}\r\n");
      out.write("	// 일을 클릭했을때 일정 정보 영역 호출하는 함수\r\n");
      out.write("	function showOnArt(year,month,date,i) {\r\n");
      out.write("		var day=days[i]\r\n");
      out.write("		var formNode=document.getElementById(\"schedule_form\");\r\n");
      out.write("		formNode.innerHTML=\"\";\r\n");
      out.write("		var hNode=document.createElement('h1');\r\n");
      out.write("		hNode.setAttribute('style','display: inline;');\r\n");
      out.write("		var dateNode=document.createTextNode(year+'.'+(month+1)+'.'+date+'.'+day);\r\n");
      out.write("		hNode.appendChild(dateNode);\r\n");
      out.write("		formNode.appendChild(hNode);\r\n");
      out.write("		var inserBt=document.createElement('button');\r\n");
      out.write("		inserBt.setAttribute('type','button');\r\n");
      out.write("		inserBt.innerHTML='<i id=\"ico\" class=\"material-icons\">edit</i>';\r\n");
      out.write("		inserBt.setAttribute('id','goButton');\r\n");
      out.write("		inserBt.setAttribute('onclick','showOnDiv('+year+','+month+','+date+')');\r\n");
      out.write("		formNode.appendChild(inserBt);\r\n");
      out.write("		var closeBt=document.createElement('button');\r\n");
      out.write("		closeBt.setAttribute('type','button');\r\n");
      out.write("		closeBt.setAttribute('onclick','hideOnArt()');\r\n");
      out.write("		closeBt.innerHTML='X';\r\n");
      out.write("		closeBt.setAttribute('id','closeButton');\r\n");
      out.write("		formNode.appendChild(closeBt);\r\n");
      out.write("		\r\n");
      out.write("		var sdiv=document.createElement('div');\r\n");
      out.write("		sdiv.setAttribute('id','sdiv');\r\n");
      out.write("		formNode.appendChild(sdiv);\r\n");
      out.write("		document.getElementById(\"on_art\").style.display = \"flex\";\r\n");
      out.write("	}\r\n");
      out.write("	// 일정 정보 영역 다시 숨겨주는 함수\r\n");
      out.write("	function hideOnArt() {\r\n");
      out.write("		document.getElementById(\"on_art\").style.display = \"none\";\r\n");
      out.write("	}\r\n");
      out.write("	// 일정 등록을 위한 폼을 호출하는 함수\r\n");
      out.write("	function showOnDiv(year, month, date) {\r\n");
      out.write("		var formNode=document.getElementById(\"input_form\");\r\n");
      out.write("		formNode.innerHTML=\"\";\r\n");
      out.write("		var hNode=document.createElement('h1');\r\n");
      out.write("		hNode.setAttribute('style','display: inline;');\r\n");
      out.write("		var dateNode=document.createTextNode('일정등록');\r\n");
      out.write("		hNode.appendChild(dateNode);\r\n");
      out.write("		formNode.appendChild(hNode);\r\n");
      out.write("		var closeBt=document.createElement('button');\r\n");
      out.write("		closeBt.setAttribute('type','button');\r\n");
      out.write("		closeBt.setAttribute('onclick','hideOnDiv()');\r\n");
      out.write("		closeBt.innerHTML='X';\r\n");
      out.write("		closeBt.setAttribute('id','closeButton');\r\n");
      out.write("		formNode.appendChild(closeBt);\r\n");
      out.write("		//input site\r\n");
      out.write("		var brNode=document.createElement('br')\r\n");
      out.write("		var hrNode1=document.createElement('hr')\r\n");
      out.write("		var hrNode2=document.createElement('hr')\r\n");
      out.write("		var sdiv=document.createElement('div');\r\n");
      out.write("		sdiv.setAttribute('id','sdiv');\r\n");
      out.write("		//title site\r\n");
      out.write("		var titleText=document.createTextNode('요약:');\r\n");
      out.write("		var titleNode=document.createElement('input');\r\n");
      out.write("		titleNode.setAttribute('type','text');\r\n");
      out.write("		titleNode.setAttribute('id','title');\r\n");
      out.write("		sdiv.appendChild(titleText);\r\n");
      out.write("		sdiv.appendChild(titleNode);\r\n");
      out.write("		sdiv.appendChild(hrNode1);\r\n");
      out.write("		//time site\r\n");
      out.write("		var smnaSelectNode=document.createElement('select');\r\n");
      out.write("		smnaSelectNode.setAttribute('id','smna');\r\n");
      out.write("		for(var i=1;i<=2;i++){\r\n");
      out.write("			var smnaOptionNode=document.createElement('option');\r\n");
      out.write("			smnaOptionNode.setAttribute('value',i);\r\n");
      out.write("			smnaOptionNode.innerHTML=i==1?'am':'pm';\r\n");
      out.write("			smnaSelectNode.appendChild(smnaOptionNode);\r\n");
      out.write("		}\r\n");
      out.write("		var stimeSelectNode=document.createElement('select');\r\n");
      out.write("		stimeSelectNode.setAttribute('id','stime');\r\n");
      out.write("		for(var i=1;i<=12;i++){\r\n");
      out.write("			var stimeOptionNode=document.createElement('option');\r\n");
      out.write("			stimeOptionNode.setAttribute('value',i);\r\n");
      out.write("			stimeOptionNode.innerHTML=i;\r\n");
      out.write("			stimeSelectNode.appendChild(stimeOptionNode);\r\n");
      out.write("		}\r\n");
      out.write("		var emnaSelectNode=document.createElement('select');\r\n");
      out.write("		emnaSelectNode.setAttribute('id','emna');\r\n");
      out.write("		for(var i=1;i<=2;i++){\r\n");
      out.write("			var emnaOptionNode=document.createElement('option');\r\n");
      out.write("			emnaOptionNode.setAttribute('value',i);\r\n");
      out.write("			emnaOptionNode.innerHTML=i==1?'am':'pm';\r\n");
      out.write("			emnaSelectNode.appendChild(emnaOptionNode);\r\n");
      out.write("		}\r\n");
      out.write("		var etimeSelectNode=document.createElement('select');\r\n");
      out.write("		etimeSelectNode.setAttribute('id','etime');\r\n");
      out.write("		for(var i=1;i<=12;i++){\r\n");
      out.write("			var etimeOptionNode=document.createElement('option');\r\n");
      out.write("			etimeOptionNode.setAttribute('value',i);\r\n");
      out.write("			etimeOptionNode.innerHTML=i;\r\n");
      out.write("			etimeSelectNode.appendChild(etimeOptionNode);\r\n");
      out.write("		}\r\n");
      out.write("		var waveNode=document.createTextNode('~');\r\n");
      out.write("		sdiv.appendChild(smnaSelectNode);\r\n");
      out.write("		sdiv.appendChild(stimeSelectNode);\r\n");
      out.write("		sdiv.appendChild(waveNode);\r\n");
      out.write("		sdiv.appendChild(emnaSelectNode);\r\n");
      out.write("		sdiv.appendChild(etimeSelectNode);\r\n");
      out.write("		sdiv.appendChild(hrNode2);\r\n");
      out.write("		//textarea site\r\n");
      out.write("		var contentText=document.createTextNode('상세설명(공백 포함 500자 미만)');\r\n");
      out.write("		var contentNode=document.createElement('textarea');\r\n");
      out.write("		contentNode.setAttribute('id','content');\r\n");
      out.write("		contentNode.setAttribute('rows','18');\r\n");
      out.write("		contentNode.setAttribute('cols','30');\r\n");
      out.write("		sdiv.appendChild(contentText);\r\n");
      out.write("		sdiv.appendChild(brNode);\r\n");
      out.write("		sdiv.appendChild(contentNode);\r\n");
      out.write("		formNode.appendChild(sdiv);\r\n");
      out.write("		//addSchedule site\r\n");
      out.write("		var submitNode=document.createElement('button');\r\n");
      out.write("		submitNode.setAttribute('id','submitBt');\r\n");
      out.write("		submitNode.setAttribute('onclick','addSchedule(new Date('+year+','+month+','+date+'))');\r\n");
      out.write("		submitNode.innerHTML='등록';\r\n");
      out.write("		\r\n");
      out.write("		formNode.appendChild(submitNode);\r\n");
      out.write("\r\n");
      out.write("		document.getElementById(\"on_input\").style.display = \"flex\";\r\n");
      out.write("	}\r\n");
      out.write("	// 일정등록 폼 다시 숨겨주는 함수\r\n");
      out.write("	function hideOnDiv() {\r\n");
      out.write("		document.getElementById(\"on_input\").style.display = \"none\";\r\n");
      out.write("	}\r\n");
      out.write("	// 일정등록을 수행하는 함수\r\n");
      out.write("	function addSchedule(nowDate){\r\n");
      out.write("		var title=document.getElementById('title');\r\n");
      out.write("		var content=document.getElementById('content');\r\n");
      out.write("		var stime=document.getElementById('stime');\r\n");
      out.write("		var etime=document.getElementById('etime');\r\n");
      out.write("		var smna=document.getElementById('smna');\r\n");
      out.write("		var emna=document.getElementById('emna');\r\n");
      out.write("		\r\n");
      out.write("		var nyear = nowDate.getFullYear();\r\n");
      out.write("		var nmonth = nowDate.getMonth()+1;\r\n");
      out.write("		var ndate = nowDate.getDate();\r\n");
      out.write("		var sdate='';\r\n");
      out.write("		sdate = nyear+'-'+nmonth+'-'+ndate;\r\n");
      out.write("		\r\n");
      out.write("		var param='idx='+idx+'&com_idx='+com_idx+'&sort='+sort+'&title='+title.value+\r\n");
      out.write("		'&content='+content.value+'&sdate='+sdate+'&stime='+stime.value+'&etime='+etime.value+\r\n");
      out.write("		'&smna='+smna.value+'&emna='+emna.value;\r\n");
      out.write("		sendRequest('addSchedule.do',param,showResult,'POST');\r\n");
      out.write("	}\r\n");
      out.write("	//일정 등록 결과를 보여주는 함수\r\n");
      out.write("	function showResult(){\r\n");
      out.write("		if(XHR.readyState==4){\r\n");
      out.write("			if(XHR.status==200){\r\n");
      out.write("				var data=XHR.responseText;\r\n");
      out.write("				data=JSON.parse(data);\r\n");
      out.write("				var msg=data.msg;\r\n");
      out.write("				alert(msg);\r\n");
      out.write("				if(msg=='등록성공'){\r\n");
      out.write("					hideOnDiv()\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"javascript:startPage(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.dto.idx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.dto.com_idx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",1)\">\r\n");
      out.write("	<section>\r\n");
      out.write("	<a href=\"goMain.do\">인덱스</a>\r\n");
      out.write("		<article id=\"under_art\">\r\n");
      out.write("			<a href=\"javascript:showOnArt()\">띄우기</a>\r\n");
      out.write("			<h1>캘린더</h1>\r\n");
      out.write("			<div id=\"month\"><div></div><h1></h1></div>\r\n");
      out.write("			<div id=\"selectSort\">\r\n");
      out.write("				<select onchange=\"changeSort(this.value)\">\r\n");
      out.write("					<option value=\"1\">개인</option>\r\n");
      out.write("					<option value=\"2\">부서</option>\r\n");
      out.write("					<option value=\"3\">회사</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div style=\"margin: 0px auto; width: 700px;\">\r\n");
      out.write("				<div class=\"weekName-div\">\r\n");
      out.write("					<label class=\"sunday\">sun</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"weekName-div\">\r\n");
      out.write("					<label class=\"monthday\">mon</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"weekName-div\">\r\n");
      out.write("					<label class=\"tuesday\">tue</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"weekName-div\">\r\n");
      out.write("					<label class=\"wednesday\">wed</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"weekName-div\">\r\n");
      out.write("					<label class=\"thursday\">thu</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"weekName-div\">\r\n");
      out.write("					<label class=\"friday\">fri</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"weekName-div\">\r\n");
      out.write("					<label class=\"saturday\">sat</label>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<table id=\"calendar\" cellspacing=\"0\">\r\n");
      out.write("			</table>\r\n");
      out.write("		</article>\r\n");
      out.write("		<article id=\"on_art\">\r\n");
      out.write("			<div id=\"schedule_form\"></div>\r\n");
      out.write("		</article>\r\n");
      out.write("		<article id=\"on_input\">\r\n");
      out.write("			<div id=\"input_form\"></div>\r\n");
      out.write("		</article>\r\n");
      out.write("	</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
